version: '3.8'

services:
  event-app:
    container_name: event-app
    build:
      context: .
      dockerfile: Dockerfile.test
    env_file:
      - ./.env
    volumes:
      - ./src:/usr/src/app/src
      - ./frontend:/usr/src/app/frontend
    ports:
      - ${PORT}:${PORT}
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    restart: unless-stopped
    depends_on:
      mysql-server:
        condition: service_healthy
    command: sh -c "(npm run serve &) && cd ./frontend && npm run serve"

  mysql-server:
    container_name: mysql-server
    image: mysql:8.0
    ports:
      - 3307:3306
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: unless-stopped
    command: --init-file /data/application/init.sql
    volumes:
      - ./scripts/init.sql:/data/application/init.sql
      - database:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

volumes:
  database:
